### ISSUE TITLE
Uncaught ReferenceError: filePath is not defined

### ISSUE THREAD

**Issue by Ervent** [fcharlie/atom-gitosc#14]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [gitosc](https://github.com/fcharlie/atom-gitosc) package 1.2.0

### Stack Trace

Uncaught ReferenceError: filePath is not defined

```
At C:\Users\ThinkPad\.atom\packages\gitosc\lib\git-file.coffee:15

ReferenceError: filePath is not defined
    at /packages/gitosc/lib/git-file.coffee:15:45)
    at Function.module.exports.GitFile.fromPath (/packages/gitosc/lib/git-file.coffee:11:9)
    at /packages/gitosc/lib/gitosc.coffee:52:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/app.asar/src/atom-environment.js:1164:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:320:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -2:08.4.0 gitosc:clone-project (input.hidden-input)
     -0:09.7.0 gitosc:open-repository (input.hidden-input)
```

### Non-Core Packages

```
drunken-php 0.2.3 
file-type-icons 1.3.3 
gitosc 1.2.0 
minimap 4.25.6 
vim-mode 0.65.1 
```

**Comment by Ervent** [comment]
上传代码失败

**Comment by fcharlie** [comment]
@Ervent 请提交到官方项目主页，这个只是镜像。
